### PR TITLE
feat(communicator): integrate the communicator, use the new events endpoint

### LINKED ISSUE #22: Integrate solution-center-communicator
We need to connect the service to an actual endpoint and use the communicator for env config.

### PR DESCRIPTION
**Pull request by cjhowald**
Fixes #22 

Note that this can't be fully tested until the new endpoint is deployed to dev.

### CODE REVIEW

**Comment by gregdeane** [comment]
Looks good. All tests pass.

**Comment by gregdeane** [comment]
👍

**Comment by gregdeane** [comment]
Happened to notice that there's an `.eslintrc.json` file in the root of the project. Probably not using this?

**Comment by cjhowald** [comment]
We should take a look at removing the communicator import and see if it still works.

**Comment by frontendherodk** [comment]
I've removed the communicator import to avoid duplicated imports in the Solution Center

**Comment by frontendherodk** [comment]
@cjhowald Can you have a quick look

**Comment by cjhowald** [comment]
👍

**Comment by frontendherodk** [comment]
👍

**Pull request merged**
