### PR TITLE
build(npm): add npm release + changelog scripts

### LINKED ISSUE #2: NPM publish

### PR DESCRIPTION
**Pull request by cjhowald**
Fixes #2 

Added release scripts. Will publish + release version 1.0 after this PR merges.

### CODE REVIEW

**Comment by cjhowald** [comment]
@dami-gg Please take a look

**Comment by dami-gg** [comment]
I've checked and it looks exactly like the scripts we have in the other repos so it looks fine to me

**Comment by dami-gg** [comment]
:+1:

**Comment by cjhowald** [comment]
👍

**Pull request merged**
