### PR TITLE
feat(json-server): add json-server as mock BE, init mock event DB

### LINKED ISSUE #11: Set up mock BE
Until the new BE endpoint is ready, we should mock it for development using [JSON server](https://github.com/typicode/json-server).

### PR DESCRIPTION
**Pull request by cjhowald**
Fixes #11. Add JSON server and `db.json` so we can mock API calls to `/events` until the backend is ready.

Notes:

- json-server is started concurrently with the webpack build on `npm start`.
- Events can be accessed at localhost:3000/events (GET, PUT, POST, etc.).
- We will strip this out before we release the initial version of the service - this is just to speed up development.
- I did not define the shape of an event in a TS class/interface as I felt that should follow in the implementation of the service. Let me know if you would prefer it to be in this PR.

### CODE REVIEW

**Comment by gregdeane** [comment]
Looks good. Just to clarify... You'll add the event class/interface when you implement the service? If so, that's fine. Just want to ensure it is added. Thx!

**Comment by gregdeane** [comment]
👍

**Comment by cjhowald** [comment]
@gregdeane Yes we will add the interface/class when we implement the service.

**Comment by cjhowald** [comment]
👍

**Pull request merged**
